FROM openjdk:17-jdk-slim
LABEL authors="Vitalii Seniuk"

ARG JAR_FILE=target/*.jar
ARG DB_HOST
ARG DB_USER
ARG DB_PASSWORD
ARG SPRING_DATA_REDIS_HOST
ARG SPRING_DATA_REDIS_PORT
ARG SPRING_DATA_REDIS_PASSWORD
ARG EUREKA_URL
ARG RABBITMQ_HOST
ARG STORAGE_BASE_PATH
ARG RABBITMQ_MOVE_QUEUE_NAME
ARG RABBITMQ_EXCHANGE_NAME
ARG RABBITMQ_ROUTING_KEY

# Set environment variables from build-time arguments
ENV DB_HOST=$DB_HOST \
    DB_USER=$DB_USER \
    DB_PASSWORD=$DB_PASSWORD \
    SPRING_DATA_REDIS_HOST=$SPRING_DATA_REDIS_HOST \
    SPRING_DATA_REDIS_PORT=$SPRING_DATA_REDIS_PORT \
    SPRING_DATA_REDIS_PASSWORD=$SPRING_DATA_REDIS_PASSWORD \
    EUREKA_URL=$EUREKA_URL \
    RABBITMQ_HOST=$RABBITMQ_HOST \
    STORAGE_BASE_PATH=$STORAGE_BASE_PATH \
    RABBITMQ_MOVE_QUEUE_NAME=$RABBITMQ_MOVE_QUEUE_NAME \
    RABBITMQ_EXCHANGE_NAME=$RABBITMQ_EXCHANGE_NAME \
    RABBITMQ_ROUTING_KEY=$RABBITMQ_ROUTING_KEY

COPY ${JAR_FILE} worker-storage-service.jar

ENTRYPOINT ["java", "-jar", "/worker-storage-service.jar"]