FROM openjdk:17-jdk-slim
LABEL authors="Vitalii Seniuk"

ARG JAR_FILE=target/*.jar
ARG DB_HOST
ARG DB_USER
ARG DB_PASSWORD
ARG SPRING_DATA_REDIS_HOST
ARG SPRING_DATA_REDIS_PORT
ARG SPRING_DATA_REDIS_PASSWORD
ARG EUREKA_URL
ARG STORAGE_BASE_PATH
ARG SPRING_RABBITMQ_HOST
ARG SPRING_RABBITMQ_PORT
ARG RABBITMQ_MOVE_QUEUE_NAME
ARG RABBITMQ_EXCHANGE_NAME
ARG RABBITMQ_ROUTING_KEY
ARG KAFKA_BOOTSTRAP_SERVERS
ARG KAFKA_TOPIC_NAME
ARG KAFKA_GROUP_ID
ARG KAFKA_REPLICATION_FACTOR
ARG MANAGEMENT_OTLP_TRACING_ENDPOINT
ARG MANAGEMENT_OTLP_METRICS_EXPORT_URL

# Set environment variables from build-time arguments
ENV DB_HOST=$DB_HOST \
    DB_USER=$DB_USER \
    DB_PASSWORD=$DB_PASSWORD \
    SPRING_DATA_REDIS_HOST=$SPRING_DATA_REDIS_HOST \
    SPRING_DATA_REDIS_PORT=$SPRING_DATA_REDIS_PORT \
    SPRING_DATA_REDIS_PASSWORD=$SPRING_DATA_REDIS_PASSWORD \
    EUREKA_URL=$EUREKA_URL \
    STORAGE_BASE_PATH=$STORAGE_BASE_PATH \
    KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS \
    KAFKA_TOPIC_NAME=$KAFKA_TOPIC_NAME \
    KAFKA_GROUP_ID=$KAFKA_GROUP_ID \
    KAFKA_REPLICATION_FACTOR=$KAFKA_REPLICATION_FACTOR \
    SPRING_RABBITMQ_HOST=$SPRING_RABBITMQ_HOST \
    SPRING_RABBITMQ_PORT=$SPRING_RABBITMQ_PORT \
    RABBITMQ_MOVE_QUEUE_NAME=$RABBITMQ_MOVE_QUEUE_NAME \
    RABBITMQ_EXCHANGE_NAME=$RABBITMQ_EXCHANGE_NAME \
    RABBITMQ_ROUTING_KEY=$RABBITMQ_ROUTING_KEY \
    MANAGEMENT_OTLP_TRACING_ENDPOINT=$MANAGEMENT_OTLP_TRACING_ENDPOINT \
    MANAGEMENT_OTLP_METRICS_EXPORT_URL=$MANAGEMENT_OTLP_METRICS_EXPORT_URL

COPY ${JAR_FILE} worker-storage-service.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/worker-storage-service.jar"]